services:
  db:
    image: postgres:15-alpine
    network_mode: "host"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-morpheus_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-morpheus_password}
      POSTGRES_DB: ${POSTGRES_DB:-morpheus_db}
      PGPORT: 5433
    ports:
      - "5433:5432" # Changed from 5432:5432 to avoid conflicts with local PostgreSQL
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5433"]
        interval: 5s
        timeout: 5s
        retries: 5

  redis:
    image: redis:7-alpine
    network_mode: "host"
    command: redis-server --requirepass ${REDIS_PASSWORD:-supersecretredis}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379" # Expose only if needed for external inspection
    healthcheck:
        test: ["CMD", "redis-cli", "-a", "$${REDIS_PASSWORD:-supersecretredis}", "ping"]
        interval: 5s
        timeout: 5s
        retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # Load environment variables from .env file
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-morpheus_user}:${POSTGRES_PASSWORD:-morpheus_password}@localhost:5433/${POSTGRES_DB:-morpheus_db}
      REDIS_URL: redis://:${REDIS_PASSWORD:-supersecretredis}@localhost:6379/0
      PROXY_ROUTER_URL: http://morpheus-router.mor.org:8082
      # Other env vars like JWT_SECRET_KEY, KMS settings etc. will be loaded from .env
    volumes:
      - ./src:/app/src # Mount src for development hot-reloading (optional)
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    network_mode: "host"
    # For development with hot-reload using uvicorn directly:
    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data: 